version: '3.1'

services:
    garudaHacks_postgres:
        container_name: garudaHacks_postgres
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres-password
        ports:
            - '5432:5432'
        volumes:
            - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
